M48
; DRILL file {KiCad 9.0.7} date 2026-09-26T10:30:42+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T10:30:42+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X168.476Y-94.755
X173.476Y-94.755
T2
X151.026Y-89.07
X154.026Y-89.07
M30
